name: Build
on:
  - push

jobs:
  build:
    name: Build using TS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Compile typescript
        run: npm run build
        working-directory: ./backend
